FROM python:3.11-slim


RUN apt-get update && apt-get install -y --no-install-recommends \
    wget=1.21.3-1+b2 \
    vim-tiny=2:9.0.1378-2 \
    && rm -rf /var/lib/apt/lists/* \
    && apt-get clean


WORKDIR /app

COPY main.py /app/

RUN pip install --no-cache-dir flask==2.3.3

CMD ["python", "main.py"]
